# site settings
title: Targosz.dev
subtitle: Embedded Developer for fun & life
email: paultargosz86@gmail.com
description: Welcome to my world. I have cookies, template meta programming <br/>and bare metal software in modern C ++
#baseurl:  # the subpath of your site, e.g. /blog
#url: "https://targosz.dev" # the base hostname & protocol for your site
author:
# street_address: 1234 Somewhere Road
# city: Nashville
# state: TN
# zip_code: 55555
# country: United States of America
# phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
# facebook_url:
github_url: https://github.com/Sickeroni
# gitlab_url: https://gitlab.com/u/andrewbanchich
# googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://www.instagram.com/sickeroni/
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
# pinterest_url:
# slack_url:
twitter_url: https://twitter.com/sickeroni

# build settings
markdown: kramdown

fullname: Paul Targosz

sass:
  style: compressed
